# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eda_games.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='eda_games.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65\x64\x61_games.proto\x1a\x1cgoogle/protobuf/struct.proto\"$\n\x11\x43reateGameRequest\x12\x0f\n\x07players\x18\x01 \x03(\t\"$\n\x12\x43reateGameResponse\x12\x0e\n\x06idgame\x18\x01 \x01(\t\"M\n\x14\x45xecuteActionRequest\x12\x0e\n\x06idgame\x18\x01 \x01(\t\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\" \n\x0e\x45ndGameRequest\x12\x0e\n\x06idgame\x18\x01 \x01(\t\"!\n\x0fPenalizeRequest\x12\x0e\n\x06idgame\x18\x01 \x01(\t\"\xeb\x01\n\x11GameStateResponse\x12\x33\n\tplay_data\x18\x01 \x03(\x0b\x32 .GameStateResponse.PlayDataEntry\x12\x16\n\x0e\x63urrent_player\x18\x02 \x01(\t\x12\x13\n\x0bnext_player\x18\x03 \x01(\t\x12*\n\tturn_data\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x1aH\n\rPlayDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct:\x02\x38\x01\x32\xed\x01\n\x0e\x45\x64\x61GameService\x12\x37\n\nCreateGame\x12\x12.CreateGameRequest\x1a\x13.CreateGameResponse\"\x00\x12<\n\rExecuteAction\x12\x15.ExecuteActionRequest\x1a\x12.GameStateResponse\"\x00\x12\x30\n\x07\x45ndGame\x12\x0f.EndGameRequest\x1a\x12.GameStateResponse\"\x00\x12\x32\n\x08Penalize\x12\x10.PenalizeRequest\x1a\x12.GameStateResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_CREATEGAMEREQUEST = _descriptor.Descriptor(
  name='CreateGameRequest',
  full_name='CreateGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='players', full_name='CreateGameRequest.players', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=85,
)


_CREATEGAMERESPONSE = _descriptor.Descriptor(
  name='CreateGameResponse',
  full_name='CreateGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idgame', full_name='CreateGameResponse.idgame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=123,
)


_EXECUTEACTIONREQUEST = _descriptor.Descriptor(
  name='ExecuteActionRequest',
  full_name='ExecuteActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idgame', full_name='ExecuteActionRequest.idgame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ExecuteActionRequest.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=202,
)


_ENDGAMEREQUEST = _descriptor.Descriptor(
  name='EndGameRequest',
  full_name='EndGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idgame', full_name='EndGameRequest.idgame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=236,
)


_PENALIZEREQUEST = _descriptor.Descriptor(
  name='PenalizeRequest',
  full_name='PenalizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idgame', full_name='PenalizeRequest.idgame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=271,
)


_GAMESTATERESPONSE_PLAYDATAENTRY = _descriptor.Descriptor(
  name='PlayDataEntry',
  full_name='GameStateResponse.PlayDataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='GameStateResponse.PlayDataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='GameStateResponse.PlayDataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=509,
)

_GAMESTATERESPONSE = _descriptor.Descriptor(
  name='GameStateResponse',
  full_name='GameStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='play_data', full_name='GameStateResponse.play_data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_player', full_name='GameStateResponse.current_player', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_player', full_name='GameStateResponse.next_player', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='turn_data', full_name='GameStateResponse.turn_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GAMESTATERESPONSE_PLAYDATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=509,
)

_EXECUTEACTIONREQUEST.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GAMESTATERESPONSE_PLAYDATAENTRY.fields_by_name['value'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GAMESTATERESPONSE_PLAYDATAENTRY.containing_type = _GAMESTATERESPONSE
_GAMESTATERESPONSE.fields_by_name['play_data'].message_type = _GAMESTATERESPONSE_PLAYDATAENTRY
_GAMESTATERESPONSE.fields_by_name['turn_data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['CreateGameRequest'] = _CREATEGAMEREQUEST
DESCRIPTOR.message_types_by_name['CreateGameResponse'] = _CREATEGAMERESPONSE
DESCRIPTOR.message_types_by_name['ExecuteActionRequest'] = _EXECUTEACTIONREQUEST
DESCRIPTOR.message_types_by_name['EndGameRequest'] = _ENDGAMEREQUEST
DESCRIPTOR.message_types_by_name['PenalizeRequest'] = _PENALIZEREQUEST
DESCRIPTOR.message_types_by_name['GameStateResponse'] = _GAMESTATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateGameRequest = _reflection.GeneratedProtocolMessageType('CreateGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMEREQUEST,
  '__module__' : 'eda_games_pb2'
  # @@protoc_insertion_point(class_scope:CreateGameRequest)
  })
_sym_db.RegisterMessage(CreateGameRequest)

CreateGameResponse = _reflection.GeneratedProtocolMessageType('CreateGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMERESPONSE,
  '__module__' : 'eda_games_pb2'
  # @@protoc_insertion_point(class_scope:CreateGameResponse)
  })
_sym_db.RegisterMessage(CreateGameResponse)

ExecuteActionRequest = _reflection.GeneratedProtocolMessageType('ExecuteActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEACTIONREQUEST,
  '__module__' : 'eda_games_pb2'
  # @@protoc_insertion_point(class_scope:ExecuteActionRequest)
  })
_sym_db.RegisterMessage(ExecuteActionRequest)

EndGameRequest = _reflection.GeneratedProtocolMessageType('EndGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDGAMEREQUEST,
  '__module__' : 'eda_games_pb2'
  # @@protoc_insertion_point(class_scope:EndGameRequest)
  })
_sym_db.RegisterMessage(EndGameRequest)

PenalizeRequest = _reflection.GeneratedProtocolMessageType('PenalizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _PENALIZEREQUEST,
  '__module__' : 'eda_games_pb2'
  # @@protoc_insertion_point(class_scope:PenalizeRequest)
  })
_sym_db.RegisterMessage(PenalizeRequest)

GameStateResponse = _reflection.GeneratedProtocolMessageType('GameStateResponse', (_message.Message,), {

  'PlayDataEntry' : _reflection.GeneratedProtocolMessageType('PlayDataEntry', (_message.Message,), {
    'DESCRIPTOR' : _GAMESTATERESPONSE_PLAYDATAENTRY,
    '__module__' : 'eda_games_pb2'
    # @@protoc_insertion_point(class_scope:GameStateResponse.PlayDataEntry)
    })
  ,
  'DESCRIPTOR' : _GAMESTATERESPONSE,
  '__module__' : 'eda_games_pb2'
  # @@protoc_insertion_point(class_scope:GameStateResponse)
  })
_sym_db.RegisterMessage(GameStateResponse)
_sym_db.RegisterMessage(GameStateResponse.PlayDataEntry)


_GAMESTATERESPONSE_PLAYDATAENTRY._options = None

_EDAGAMESERVICE = _descriptor.ServiceDescriptor(
  name='EdaGameService',
  full_name='EdaGameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=512,
  serialized_end=749,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGame',
    full_name='EdaGameService.CreateGame',
    index=0,
    containing_service=None,
    input_type=_CREATEGAMEREQUEST,
    output_type=_CREATEGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExecuteAction',
    full_name='EdaGameService.ExecuteAction',
    index=1,
    containing_service=None,
    input_type=_EXECUTEACTIONREQUEST,
    output_type=_GAMESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndGame',
    full_name='EdaGameService.EndGame',
    index=2,
    containing_service=None,
    input_type=_ENDGAMEREQUEST,
    output_type=_GAMESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Penalize',
    full_name='EdaGameService.Penalize',
    index=3,
    containing_service=None,
    input_type=_PENALIZEREQUEST,
    output_type=_GAMESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDAGAMESERVICE)

DESCRIPTOR.services_by_name['EdaGameService'] = _EDAGAMESERVICE

# @@protoc_insertion_point(module_scope)
