# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: edagames_grpc/eda_games.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='edagames_grpc/eda_games.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1d\x65\x64\x61games_grpc/eda_games.proto\x1a\x1cgoogle/protobuf/struct.proto\"$\n\x11\x43reateGameRequest\x12\x0f\n\x07players\x18\x01 \x03(\t\"\x18\n\x06Idgame\x12\x0e\n\x06idgame\x18\x01 \x01(\t\"M\n\x14\x45xecuteActionRequest\x12\x0e\n\x06idgame\x18\x01 \x01(\t\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"g\n\x11GameStartResponse\x12\x0e\n\x06idgame\x18\x01 \x01(\t\x12\x16\n\x0e\x63urrent_player\x18\x02 \x01(\t\x12*\n\tturn_data\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x94\x01\n\x11GameStateResponse\x12*\n\tplay_data\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0f\n\x07game_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63urrent_player\x18\x03 \x01(\t\x12*\n\tturn_data\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct2\xdb\x01\n\x0e\x45\x64\x61GameService\x12\x36\n\nCreateGame\x12\x12.CreateGameRequest\x1a\x12.GameStartResponse\"\x00\x12<\n\rExecuteAction\x12\x15.ExecuteActionRequest\x1a\x12.GameStateResponse\"\x00\x12(\n\x07\x45ndGame\x12\x07.Idgame\x1a\x12.GameStateResponse\"\x00\x12)\n\x08Penalize\x12\x07.Idgame\x1a\x12.GameStateResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_CREATEGAMEREQUEST = _descriptor.Descriptor(
  name='CreateGameRequest',
  full_name='CreateGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='players', full_name='CreateGameRequest.players', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=99,
)


_IDGAME = _descriptor.Descriptor(
  name='Idgame',
  full_name='Idgame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idgame', full_name='Idgame.idgame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=125,
)


_EXECUTEACTIONREQUEST = _descriptor.Descriptor(
  name='ExecuteActionRequest',
  full_name='ExecuteActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idgame', full_name='ExecuteActionRequest.idgame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='ExecuteActionRequest.data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=204,
)


_GAMESTARTRESPONSE = _descriptor.Descriptor(
  name='GameStartResponse',
  full_name='GameStartResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idgame', full_name='GameStartResponse.idgame', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_player', full_name='GameStartResponse.current_player', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='turn_data', full_name='GameStartResponse.turn_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=309,
)


_GAMESTATERESPONSE = _descriptor.Descriptor(
  name='GameStateResponse',
  full_name='GameStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='play_data', full_name='GameStateResponse.play_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_id', full_name='GameStateResponse.game_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_player', full_name='GameStateResponse.current_player', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='turn_data', full_name='GameStateResponse.turn_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=460,
)

_EXECUTEACTIONREQUEST.fields_by_name['data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GAMESTARTRESPONSE.fields_by_name['turn_data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GAMESTATERESPONSE.fields_by_name['play_data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_GAMESTATERESPONSE.fields_by_name['turn_data'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['CreateGameRequest'] = _CREATEGAMEREQUEST
DESCRIPTOR.message_types_by_name['Idgame'] = _IDGAME
DESCRIPTOR.message_types_by_name['ExecuteActionRequest'] = _EXECUTEACTIONREQUEST
DESCRIPTOR.message_types_by_name['GameStartResponse'] = _GAMESTARTRESPONSE
DESCRIPTOR.message_types_by_name['GameStateResponse'] = _GAMESTATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateGameRequest = _reflection.GeneratedProtocolMessageType('CreateGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMEREQUEST,
  '__module__' : 'edagames_grpc.eda_games_pb2'
  # @@protoc_insertion_point(class_scope:CreateGameRequest)
  })
_sym_db.RegisterMessage(CreateGameRequest)

Idgame = _reflection.GeneratedProtocolMessageType('Idgame', (_message.Message,), {
  'DESCRIPTOR' : _IDGAME,
  '__module__' : 'edagames_grpc.eda_games_pb2'
  # @@protoc_insertion_point(class_scope:Idgame)
  })
_sym_db.RegisterMessage(Idgame)

ExecuteActionRequest = _reflection.GeneratedProtocolMessageType('ExecuteActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXECUTEACTIONREQUEST,
  '__module__' : 'edagames_grpc.eda_games_pb2'
  # @@protoc_insertion_point(class_scope:ExecuteActionRequest)
  })
_sym_db.RegisterMessage(ExecuteActionRequest)

GameStartResponse = _reflection.GeneratedProtocolMessageType('GameStartResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTARTRESPONSE,
  '__module__' : 'edagames_grpc.eda_games_pb2'
  # @@protoc_insertion_point(class_scope:GameStartResponse)
  })
_sym_db.RegisterMessage(GameStartResponse)

GameStateResponse = _reflection.GeneratedProtocolMessageType('GameStateResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATERESPONSE,
  '__module__' : 'edagames_grpc.eda_games_pb2'
  # @@protoc_insertion_point(class_scope:GameStateResponse)
  })
_sym_db.RegisterMessage(GameStateResponse)



_EDAGAMESERVICE = _descriptor.ServiceDescriptor(
  name='EdaGameService',
  full_name='EdaGameService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=463,
  serialized_end=682,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGame',
    full_name='EdaGameService.CreateGame',
    index=0,
    containing_service=None,
    input_type=_CREATEGAMEREQUEST,
    output_type=_GAMESTARTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExecuteAction',
    full_name='EdaGameService.ExecuteAction',
    index=1,
    containing_service=None,
    input_type=_EXECUTEACTIONREQUEST,
    output_type=_GAMESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndGame',
    full_name='EdaGameService.EndGame',
    index=2,
    containing_service=None,
    input_type=_IDGAME,
    output_type=_GAMESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Penalize',
    full_name='EdaGameService.Penalize',
    index=3,
    containing_service=None,
    input_type=_IDGAME,
    output_type=_GAMESTATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EDAGAMESERVICE)

DESCRIPTOR.services_by_name['EdaGameService'] = _EDAGAMESERVICE

# @@protoc_insertion_point(module_scope)
